// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

namespace backend.Migrations
{
    [DbContext(typeof(FashionContext))]
    partial class FashionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("backend.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<int>("CountryId");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);

                    b.Property<string>("Street");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, Name = "Dames" },
                        new { Id = 2, Name = "Heren" },
                        new { Id = 3, Name = "Schoenen" },
                        new { Id = 4, Name = "Shirts" },
                        new { Id = 5, Name = "Jeans" },
                        new { Id = 6, Name = "Hoodies" },
                        new { Id = 7, Name = "Vesten" },
                        new { Id = 8, Name = "Adidas" },
                        new { Id = 9, Name = "Nike" },
                        new { Id = 10, Name = "HRFashion" },
                        new { Id = 11, Name = "Puma" },
                        new { Id = 12, Name = "Timberland" },
                        new { Id = 13, Name = "Reebok" },
                        new { Id = 14, Name = "Vans" }
                    );
                });

            modelBuilder.Entity("backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new { Id = 1, Name = "Nederland" }
                    );
                });

            modelBuilder.Entity("backend.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("DiscountPercentage");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("ProductId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<int>("StatusId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("ImageName");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductSizeId");

                    b.HasKey("Id");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Amount = 20, Color = "Wit", Description = "Deze gestroomlijnde schoen, in 1971 speciaal ontworpen voor tennislegende Stan Smith, heeft een bijzondere plek in de stijlgeschiedenis. Het gladde bovenwerk van volnerfleer met geperforeerde 3-Stripes en de rubberen loopzool in een bijpassende kleur hebben van de low-top een waar sneakericoon gemaakt.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/4edaa6d5b65a40d19f20a7fa00ea641f_9366/Stan_Smith_Schoenen_wit_M20325_01_standard.jpg", Name = "Stan Smith Schoenen", Price = 94.95m, ProductSizeId = 3 },
                        new { Id = 2, Amount = 20, Color = "Wit", Description = "Deze jaren 70-sneaker begon zijn leven als een basketbalschoen die het hele veld beheerste. Het duurde niet lang voor hij binnendrong in de skateboardwereld en die van de streetstyle (om nog maar te zwijgen over het hoofdpodium van de hiphop). De schoen houdt z'n look klassiek met een gecoat leren bovenwerk. Met alle authentieke details, waaronder gekartelde 3-Stripes en de karakteristieke rubberen shell-toe.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/d285610e30664900b857a7fa00ed0201_9366/Superstar_Schoenen_wit_C77124_01_standard.jpg", Name = "Adidas Superstar", Price = 99.95m, ProductSizeId = 3 },
                        new { Id = 3, Amount = 20, Color = "Roze", Description = "Deze schoen verandert het klassieke silhouet van de Samba in een trendy platformsneaker met een vrouwelijke twist. Het leren bovenwerk is bedrukt met een slangenhuidreliëf en de dikke platformzool maakt 'm het hoogtepunt van trendy stijl.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/b645e657b95646b3a1c7a90000f6b358_9366/SAMBAROSE_Schoenen_roze_B28164_01_standard.jpg", Name = "Adidas SambaRose", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 4, Amount = 20, Color = "Wit", Description = "De legende leeft voort in de Nike Air Force 1 '07 damesschoen, een moderne uitvoering van het icoon waarin klassieke stijl en moderne, frisse details samenkomen.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/up7tdgif09cvhfiuxtta/air-force-1-07-damesschoen-yATYOKl8.jpg", Name = "Nike Air Force 1", Price = 100.00m, ProductSizeId = 3 },
                        new { Id = 5, Amount = 20, Color = "Goud", Description = "De op ruimtereizen geïnspireerde Nike Air VaporMax 19 'Space Walk' verlegt grenzen, waardoor het lijkt of je op lucht loopt. Met een buitenaardse kleurencombinatie wordt de Nike Air VaporMax 19 jouw beste schoen ooit.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/ywxe20sregbymtn7eeow/air-vapormax-2019-damesschoen-FK51kR.jpg", Name = "Nike Air VaporMax ", Price = 190.00m, ProductSizeId = 3 },
                        new { Id = 6, Amount = 20, Color = "Roze", Description = "Deze versie van de Nike Air Max 95 behoudt de iconische look van de AM95, maar heeft een voering van zachte, dikke stof om je voeten warm te houden als de temperatuur daalt.", ImageName = "https://www.nike.com/nl/t/air-max-95-winterized-damesschoen-gkDT6T/BV0309-200", Name = "Nike Air Max 95 ", Price = 180.00m, ProductSizeId = 3 },
                        new { Id = 7, Amount = 20, Color = "Zwart", Description = "Met een eigen draai aan een van PUMA's meest herkenbare modellen heeft deze Basket-uitvoering all kenmerken van de iconische versie, zoals de beroemde smalle tooling en lange, strakke lijnen, maar dan met een brede, strikachtige sluiting zodat je zowel een stoer als vrouwelijk gevoel hebt in deze coole, casual look.", ImageName = "https://pumaimages.azureedge.net/images/363073/01/fnd/EEA/h/600/w/600", Name = "Puma Basket Heart", Price = 70.00m, ProductSizeId = 3 },
                        new { Id = 8, Amount = 20, Color = "Wit", Description = "De Thunder Leather betoont eer aan eerdere samenwerkingen en modellen die vooruit waren op hun tijd. Geïnspireerd door CELL System hardloopmodellen van de jaren '90 en de samenwerking PUMA x McQueen kreeg dit vernieuwde paar een overdadige, grove, ongegeneerde uitstraling. De uitvergrote retro tooling, de opgeblazen proporties en de schreeuwende kleurvlakken reserveren voor de Thunder een plek in de internationale pistes.", ImageName = "https://pumaimages.azureedge.net/images/370682/01/fnd/EEA/h/600/w/600", Name = "Puma Thunder Leather", Price = 130.00m, ProductSizeId = 3 },
                        new { Id = 9, Amount = 20, Color = "Zwart", Description = "Geïnspireerd door een van de meest bekende damesmode-accessoires, de STRIK, combineert deze koningin met kleurvlakken van de PUMA Suedes stoutmoedigheid met het vrouwelijke. Volledig suede, volledige stijl ... volledig goed.", ImageName = "https://pumaimages.azureedge.net/images/367453/02/fnd/EEA/h/600/w/600", Name = "Puma Suede Bow Block", Price = 70.00m, ProductSizeId = 3 },
                        new { Id = 10, Amount = 20, Color = "Roze", Description = "Klassiek vakmanschap vormt deze nieuwe, stoere Timberland® 6-inch boot.", ImageName = "https://images.timberland.com/is/image/TimberlandEU/A1K3Z662-alt1?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=06dRL3&wid=773&hei=773&fmt=jpg", Name = "Premium 6-Inch Boots", Price = 153.95m, ProductSizeId = 3 },
                        new { Id = 11, Amount = 20, Color = "Bruin", Description = "Klassiek vakmanschap vormt deze nieuwe, stoere Timberland® 6-inch boot.", ImageName = "https://images.timberland.com/is/image/TimberlandEU/A1SI1231-alt1?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=miRR73&wid=773&hei=773&fmt=jpg", Name = "Original 6-Inch Boots", Price = 180.00m, ProductSizeId = 3 },
                        new { Id = 12, Amount = 20, Color = "Zwart", Description = "De Daytona DMX debuteerde in 2000 met een stevige en opvallende look. Deze hoge schoenen pronken met een strak en gestroomlijnd bovenwerk. Ze hebben DMX-schokdemping voor comfort dat de hele dag duurt.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwf833e1a9/zoom/CN8386_03_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Daytona DMX", Price = 119.95m, ProductSizeId = 3 },
                        new { Id = 13, Amount = 20, Color = "Wit", Description = "Je hoort er helemaal bij in deze nieuwe uitvoering van onze klassieke Club C schoen. Het bovenwerk van zacht leer zorgt voor superieure ondersteuning en kwaliteit. De middenzool biedt schokdemping bij iedere stap en het tijdloze Reebok venster met logo geeft 'm een casual en toch elegante stijl.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwc4a498af/zoom/AR0456_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Club C 85", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 14, Amount = 20, Color = "Rood", Description = "Het satijnen Festival Pack geeft met zijn weelderige satijnen afwerking en sierlijke details het traditionele gebloemde brokaat een Californische look. De satijnen Festival Sk8-Hi Reissue beschikt over de perfecte hoeveelheid glans en weelderigheid. Het is een combinatie van de legendarische hoge schoen van Vans met een bovenwerk van stevig suède en textiel, een verstevigde neus tegen slijtage, een gevoerde kraag voor ondersteuning en flexibiliteit en de kenmerkende rubberen wafelzool.", ImageName = "https://images.vans.com/is/image/VansEU/VN0A2XSBULP-HERO?$PDP-FULL-IMAGE$", Name = "Vans Satin SK8-Hi", Price = 100.00m, ProductSizeId = 3 },
                        new { Id = 15, Amount = 20, Color = "Rood", Description = "De Old Skool, de klassieke skateschoen van Vans en de eerste met de iconische Side Stripe, is een lage veterschoen met een bovenkant van stevig canvas, een verstevigde neus tegen slijtage, een gevoerde kraag voor ondersteuning en flexibiliteit en de kenmerkende rubberen wafelzool.", ImageName = "https://images.vans.com/is/image/VansEU/VN0A38G1UKZ-HERO?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=z-pQx3&wid=843&hei=843&fmt=jpg", Name = "Vans Old School", Price = 64.00m, ProductSizeId = 3 },
                        new { Id = 16, Amount = 20, Color = "Zwart", Description = "Deze longsleeve heeft authentieke historische stijl. Contrasterende 3-Stripes en een Trefoil-logo creëren een moderne, sportieve look. Door de stretchy katoenen jersey voelt 't shirt zacht aan.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/33343cdd35414a8aadc5a991010dc7a2_9366/3-Stripes_T-shirt_zwart_DV2608_01_laydown.jpg", Name = "Adidas 3-Stripes longsleeve", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 17, Amount = 20, Color = "Roze", Description = "Dit dames-T-shirt krijgt een update voor het nu, maar blijft trouw aan de authentieke sport-looks. Het ruime shirt is simpelweg een klassieker, met de contrasterende logodetails zoals 3-Stripes op de mouwen en een klein Trefoil-logo op de borst. Gemaakt van katoenen jersey voor een zacht gevoel.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/6800c63ae4724fe296e8a8f000c14516_9366/3-Stripes_T-shirt_rood_DH3141_01_laydown.jpg", Name = "Adidas 3-Stripe T-Shirt", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 18, Amount = 20, Color = "Rood", Description = "Dit T-shirt is gemaakt van zachte, 100% biologisch katoenen jersey. Het heeft een relaxte pasvorm voor een hele dag comfort.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/8e2ba758ac1f4740b038a93e012b292d_9366/Coeeze_T-shirt_rood_DU7189_01_laydown.jpg", Name = "Adidas Sporting T-Shirt", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 19, Amount = 20, Color = "Grijs", Description = "De Nike Essential Cropped damestop met korte mouwen is gemaakt van zacht materiaal en heeft een kort design dat altijd comfortabel zit en fijn met laagjes gedragen kan worden.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/vmcwgqxxtqaztzntbtoe/essential-cropped-damestop-met-korte-mouwen-fpgVjn.jpg", Name = "Nike Essential Cropped", Price = 22.95m, ProductSizeId = 3 },
                        new { Id = 20, Amount = 20, Color = "Zwart", Description = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/tlhip5ivgvffmmznd58o/sportswear-metallic-damestop-met-korte-mouwen-r2FSRc.jpg", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/tlhip5ivgvffmmznd58o/sportswear-metallic-damestop-met-korte-mouwen-r2FSRc.jpg", Name = "NiKe Sportswear T-Shirt", Price = 38.00m, ProductSizeId = 3 },
                        new { Id = 21, Amount = 20, Color = "Wit", Description = "Damestop met korte mouwen", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/xzjwgaqwrnnmpn7qyku1/air-damestop-met-korte-mouwen-SmsZMd.jpg", Name = "Nike Air T-Shirt", Price = 35.00m, ProductSizeId = 3 },
                        new { Id = 22, Amount = 20, Color = "Wit", Description = "We hebben nieuwe uitrusting voor onze meest legendarische bemanning. De lifestyle-producten van PUMA zijn geïnspireerd op sport en bieden toch een slanke, trendy look.", ImageName = "https://pumaimages.azureedge.net/images/579272/01/fnd/PNA/h/600/w/600", Name = "Puma x Pepsi AOP Crop Tee", Price = 24.99m, ProductSizeId = 3 },
                        new { Id = 23, Amount = 20, Color = "Roze", Description = "Bereid u voor op topprestaties in deze hypermoderne trainingstop.", ImageName = "https://pumaimages.azureedge.net/images/516664/07/fnd/PNA/h/600/w/600", Name = "Puma Sport T-Shirt", Price = 24.95m, ProductSizeId = 3 },
                        new { Id = 24, Amount = 20, Color = "Wit", Description = "Een mode-icoon ontmoet een straaticoon in onze PUMA Suede-samenwerking met KARL LAGERFELD.", ImageName = "https://pumaimages.azureedge.net/images/577575/02/fnd/PNA/h/600/w/600", Name = "Puma x Karl T-Shirt ", Price = 34.99m, ProductSizeId = 3 },
                        new { Id = 25, Amount = 20, Color = "Wit", Description = "Het slanke shirt heeft een oversized Reebok logo op de borst.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwd4e96262/zoom/DP6692_01_standard.jpg?sh=600&strip=false&sw=600", Name = "Reebok Logo T-Shirt", Price = 24.95m, ProductSizeId = 3 },
                        new { Id = 26, Amount = 20, Color = "Zwart", Description = "De stijl van gister helemaal van nu. Dit korte dames-T-shirt houdt de look simpel en de uitstraling relaxed. Het retro Vector-logo staat trots op de voorkant van dit katoenen T-shirt.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwdee0d937/zoom/DX3943_01_standard.jpg?sh=600&strip=false&sw=600", Name = "Reebok Classica T-Shirt", Price = 24.95m, ProductSizeId = 3 },
                        new { Id = 27, Amount = 20, Color = "Wit", Description = "De Spotted Boxy Tee is van een zware kwaliteit 100% katoenjersey. Op de voorkant van het shirt prijkt een bijzonder Vans-logo.", ImageName = "https://images.vans.com/is/image/VansEU/VN0A3T8YFS8-ALT9?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=m1pQn3&wid=843&hei=843&fmt=jpg", Name = "Vans Spotted Boxy Tee", Price = 30.00m, ProductSizeId = 3 },
                        new { Id = 28, Amount = 20, Color = "Bruin", Description = "De Design Assembly-collectie combineert vooruitstrevend modedesign met een streetlook en brengt stijlvolle kleding met details. De Junction Top heeft de comfortabele, behaaglijke en oversized pasvorm van herenkleding waar we zo van houden, gecombineerd met een vrouwelijke touch.", ImageName = "https://images.vans.com/is/image/VansEU/VN0A3T9RUOH-ALT9?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=JkIQH3&wid=843&hei=843&fmt=jpg", Name = "Vans Junction Top", Price = 40.00m, ProductSizeId = 3 },
                        new { Id = 29, Amount = 20, Color = "Blauw", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/GS/12/1N/06/BK/12/GS121N06B-K12@12.1.jpg", Name = "Super Skinny Jeans", Price = 39.99m, ProductSizeId = 3 },
                        new { Id = 30, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NL/02/1N/0B/PQ/11/NL021N0BP-Q11@15.jpg", Name = "Zwarte Jeans", Price = 27.95m, ProductSizeId = 3 },
                        new { Id = 31, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/TP/72/1N/09/QQ/11/TP721N09Q-Q11@17.1.jpg", Name = "Katoene Skinny Jeans", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 32, Amount = 20, Color = "Grijs", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/EV/B2/1N/00/DC/11/EVB21N00D-C11@12.jpg", Name = "Skinny Fit Denim", Price = 24.45m, ProductSizeId = 3 },
                        new { Id = 33, Amount = 20, Color = "Rood", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NM/32/1N/0D/KG/11/NM321N0DK-G11@12.jpg", Name = "Katoene Jeans", Price = 19.95m, ProductSizeId = 3 },
                        new { Id = 34, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/BE/J2/1N/01/0T/11/BEJ21N010-T11@21.jpg", Name = "Gestreepte Skinny Jeans", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 35, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/ON/32/1N/06/QQ/11/ON321N06Q-Q11@14.jpg", Name = "Skiny Biker Jeans", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 36, Amount = 20, Color = "Blauw", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/ON/32/1N/0U/8K/11/ON321N0U8-K11@16.jpg", Name = "Skinny Fit Jeans", Price = 45.00m, ProductSizeId = 3 },
                        new { Id = 37, Amount = 20, Color = "Wit", Description = "Deze dameshoodie is geïnspireerd op looks die zijn opgegraven uit de archieven van adidas. De relaxte pullover is gemaakt van French terry badstof en heeft een trendy korter model.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/7f848cc99cb440ba9bbaa9a60149a2ac_9366/Cropped_Hoodie_wit_DX2321_01_laydown.jpg", Name = "Adidas Cropped Hoodie", Price = 59.95m, ProductSizeId = 3 },
                        new { Id = 38, Amount = 20, Color = "Roze", Description = "Een hoodie boordevol adidas-energie. De opvallende contrasterende graphics zijn niet te missen op de zachte French terry badstof. Het lange model geeft 'm niet alleen een casual, moderne uitstraling, maar biedt ook extra bedekking.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/cf378368ae9b470898b5a966013ef10e_9366/Graphic_Hoodie_roze_DW8019_01_laydown.jpg", Name = "Adidas Graphic Hoodie", Price = 54.95m, ProductSizeId = 3 },
                        new { Id = 39, Amount = 20, Color = "Geel", Description = "Een sportieve basic, doordrenkt met een moderne spirit. Dit damessweatshirt barst van de authentieke adidas-stijl dankzij een oversized Trefoil-logo op de voorkant.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/ae25d42b72c04d80bfe8a8c000e26c6e_9366/Trefoil_Hoodie_oranje_DH3138_01_laydown.jpg", Name = "Adidas Trefoil Hoodie", Price = 34.95m, ProductSizeId = 3 },
                        new { Id = 40, Amount = 20, Color = "Roze", Description = "Roze Retro Hoodie", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/1J/09/2J/11/NI121J092-J11@4.png", Name = "Nike Retro Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 41, Amount = 20, Color = "Wit", Description = "Super mooie Nike Hoodie", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/1J/09/0C/11/NI121J090-C11@14.jpg", Name = "Nike Cropped Hoodie", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 42, Amount = 20, Color = "Roze", Description = "Nike Hoodie voor de dames", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/1J/09/UG/11/NI121J09U-G11@5.png", Name = "Nike Classic Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 43, Amount = 20, Color = "Wit", Description = "Combineer de legging of sweatpants die je figuur omhult met deze cropped hoodie van fleece hoodie voor die echt onoverwinnelijke sportieve street-look.", ImageName = "https://pumaimages.azureedge.net/images/845151/01/fnd/EEA/h/600/w/600", Name = "Puma Cropped Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 44, Amount = 20, Color = "Zwart", Description = "Maak het meeste van je stijl en ga voor het grootste comfort met deze cropped pullover-sweater uitgevoerd in warme, zachte fleece van katoenmix.", ImageName = "https://pumaimages.azureedge.net/images/845146/02/fnd/EEA/h/600/w/600", Name = "Puma Fleece Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 45, Amount = 20, Color = "Roze", Description = "Deze innovatieve vrouwelijke hoodie - perfect voor training - zal zeker blijvend opvallen.", ImageName = "https://pumaimages.azureedge.net/images/518059/02/fnd/EEA/h/600/w/600", Name = "Puma P Hoodie", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 46, Amount = 20, Color = "Zwart", Description = "Een terugblik op de goede oude tijd. Dit damessweatshirt houdt de look simpel. Het retro Vector-logo staat trots voorop. Contrasterende details geven deze zachte fleecetrui een verfrissende uitstraling.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwe1d56102/zoom/DT7199_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Classic Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 47, Amount = 20, Color = "Wit", Description = "Deze hoodie is geïnspireerd op de opvallende, schuine lijnen van adidas Equipment-stijl uit de jaren 90. De geometrische 3-Stripes zijn gemaakt van badstof voor extra textuur.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/1eee042d47604faa87f5a93c011d2012_9366/Zip_Hoodie_wit_DU9540_01_laydown.jpg", Name = "Adidas Zip Hoodie", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 48, Amount = 20, Color = "Roze", Description = "Deze zachte hoodie heeft een hoge halslijn en een ruime capuchon voor volledige bedekking om 'in the zone' te komen. ", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/ee3fd1bfbe704ef89521a9910157a3ad_9366/adidas_Z_N_E__Fast_Release_Hoodie_roze_DT9397_01_laydown.jpg", Name = "Adidas Sport Vest", Price = 59.95m, ProductSizeId = 3 },
                        new { Id = 49, Amount = 20, Color = "Zwart", Description = "Zacht comfort voor na je workout. Deze sportieve, moderne hoodie heeft een behaaglijk relaxte pasvorm met verlaagde schouders. Het model van een gebreide katoenmix is afgewerkt met adidas-graphics en een lange ritssluiting. ", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/016fca67ea8e4b81bea6a981013da03a_9366/Sport_2_Street_Knit_Hoodie_zwart_DV0780_01_laydown.jpg", Name = "Adidas Street Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 50, Amount = 20, Color = "Roze", Description = "Zacht comfort vest voor alle gelegenheden", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/1J/07/1J/12/NI121J071-J12@6.1.png", Name = "Nike Gym Vest", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 51, Amount = 20, Color = "Wit", Description = "Zacht comfort voor na je workout.", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/1I/00/6Q/11/NI121I006-Q11@1.1.jpg", Name = "Nike Sport Vest", Price = 34.95m, ProductSizeId = 3 },
                        new { Id = 52, Amount = 20, Color = "Wit", Description = "De Reebok Archive maakt een comeback met de klassieke lijnen van dit vest", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw4a96c026/zoom/DH1343_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Vest", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 53, Amount = 20, Color = "Zwart", Description = "De Nike Air Max Plus herenschoen doet denken aan de legendarische Tuned Air demping en de energieke designlijnen van het origineel uit 1998.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,q_80,w_440/lggqeeldzz7qlodfybfp/air-max-plus-herenschoen-F5SqNr.jpg", Name = "Nike Air Max Plus", Price = 169.99m, ProductSizeId = 3 },
                        new { Id = 54, Amount = 20, Color = "Wit", Description = "De Nike Air VaporMax Utility is vernieuwd om natte en donkere weersomstandigheden te kunnen trotseren.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,q_80,w_440/wkwbsvqqfflqfxdsap5k/air-vapormax-utility-herenschoen-PTmtGw.jpg", Name = "Nike Air VaporMax Utility", Price = 209.95m, ProductSizeId = 3 },
                        new { Id = 55, Amount = 20, Color = "Zwart", Description = "De Air Jordan 1 Mid herenschoen is geïnspireerd op het origineel uit 1985 en grijpt terug op de revolutionaire schoen die MJ droeg tijdens zijn eerste seizoen en zijn eerste All-Star wedstrijd.", ImageName = "https://c.static-nike.com/a/images/f_auto,b_rgb:f5f5f5,w_880/z504xdwoibpikjwehvb4/air-jordan-1-mid-herenschoen-VrTWX9K1.jpg", Name = "Nike Air Jordan 1 Mid", Price = 109.99m, ProductSizeId = 3 },
                        new { Id = 56, Amount = 20, Color = "Zwart", Description = "Straatwaardige stijl bomvol innovatie. Deze op hardlopen geïnspireerde schoen omsluit de voet met een bovenwerk van gebreid textiel dat schittert met typische NMD-details.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/7abb75949dad481a9084a9740116d6d8_9366/NMD_R1_Schoenen_zwart_BD7745_07_standard.jpg", Name = "Adidas NMD_R1", Price = 149.95m, ProductSizeId = 3 },
                        new { Id = 57, Amount = 20, Color = "Wit", Description = "", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/e31254939f2d4a998cd9a91500e5298f_9366/EQT_Support_91_18_Schoenen_zwart_AQ1037_01_standard.jpg", Name = "Adidas EQT", Price = 89.95m, ProductSizeId = 3 },
                        new { Id = 58, Amount = 20, Color = "Grijs", Description = "Voel elke stap, push jezelf en houd je absoluut niet in. Blijf doorvechten tot de finish. Deze neutrale hardloopschoenen voor heren gebruiken de energieteruggevende Boost-demping voor een krachtige afzet bij iedere voetlanding.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/7102f1385cea40d69878a80f009bb34c_9366/Ultraboost_Schoenen_grijs_BB6167_01_standard.jpg", Name = "Adidas Ultra Boots", Price = 89.95m, ProductSizeId = 3 },
                        new { Id = 59, Amount = 20, Color = "Grijs", Description = "PUMA Hoops heeft voor jou het nieuwste in de Clyde Court-collectie: the Clyde Court Peace on Earth. Deze versie haalt zijn inspiratie uit het kerstseizoen en de hoop voor vrede op aarde. ", ImageName = "https://pumaimages.azureedge.net/images/191896/01/fnd/EEA/h/600/w/600", Name = "Puma Clyde Court Peace", Price = 119.95m, ProductSizeId = 3 },
                        new { Id = 60, Amount = 20, Color = "Zwart", Description = "In de IGNITE Limitless Knit zijn zeer technische hardloopvoorzieningen gecombineerd met de designmentaliteit en -attitude van moderne straatkleding. Dit model biedt een hoogwaardige demping en een goed energierendement met IGNITE-schuim over de volledige lengte van de tussenzool.", ImageName = "https://pumaimages.azureedge.net/images/189987/02/fnd/EEA/h/600/w/600", Name = "Puma Ignite", Price = 119.95m, ProductSizeId = 3 },
                        new { Id = 61, Amount = 20, Color = "Wit", Description = "Deze versie van de Suede geeft een draai aan PUMA's bekendste model en heeft alle kenmerken van de iconische versie, zoals de bekende dunne tooling en PUMA Formstrip aan de zijkant, maar heeft daarbij strakke monochrome lijnen voor een extra modieuze street-look.", ImageName = "https://pumaimages.azureedge.net/images/366287/01/fnd/EEA/h/600/w/600", Name = "Puma Suede", Price = 119.95m, ProductSizeId = 3 },
                        new { Id = 62, Amount = 20, Color = "Bruin", Description = "Een stoere klassieker met ongelooflijk comfort - na 40 jaar is onze iconische 6-inch Timberland®-boot nog steeds een klassieker die staat voor waar vakmanschap.", ImageName = "https://images.timberland.com/is/image/TimberlandEU/10061713-alt1?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=V44RN3&wid=773&hei=773&fmt=jpg", Name = "Timberland Premium 6-Inch", Price = 219.95m, ProductSizeId = 3 },
                        new { Id = 63, Amount = 20, Color = "Beige", Description = "Een stoere klassieker met ongelooflijk comfort - na 40 jaar is onze iconische 6-inch Timberland®-boot nog steeds een klassieker die staat voor waar vakmanschap.", ImageName = "https://images.timberland.com/is/image/TimberlandEU/A1BBLE82-alt1?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=salRB2&wid=773&hei=773&fmt=jpg", Name = "Timberland Premium 6-Inch", Price = 219.95m, ProductSizeId = 3 },
                        new { Id = 64, Amount = 20, Color = "Wit", Description = "Je hoort er helemaal bij in deze nieuwe uitvoering van onze klassieke Club C schoen. Het bovenwerk van zacht leer zorgt voor superieure ondersteuning en kwaliteit.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw32abaa19/zoom/AR0459_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Classic", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 65, Amount = 20, Color = "Zwart", Description = "Performance, duurzaamheid en comfort komen samen in deze uitvoering van de Nano-trainingsschoen.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw8d26ba35/zoom/M43438_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Crossfit Nano", Price = 119.95m, ProductSizeId = 3 },
                        new { Id = 66, Amount = 20, Color = "Zwart", Description = "Blijf altijd bij de tijd. Het bovenwerk van zacht leer geeft je superieur comfort. De gesneden EVA-middenzool biedt lichte schokdemping. De gevormde PU-inlegzool biedt comfort en duurzaamheid.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dwd74ccae0/zoom/2267_01_standard.jpg?sh=2000&strip=false&sw=2000", Name = "Reebok Classic Leather", Price = 89.95m, ProductSizeId = 3 },
                        new { Id = 67, Amount = 20, Color = "Zwart", Description = "De Vans Sk8-Hi is een lichte, hoge veterschoen. De gevoerde hiel zorgt voor extra comfort, de verstevigde neus kan tegen een stootje en de gevoerde boorden staan garant voor steun en een flexibel draagcomfort.", ImageName = "https://images.vans.com/is/image/VansEU/VN000D5IB8C-HERO?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=zcvR13&wid=840&hei=840&fmt=jpg", Name = "Vans Sk8-Hi Schoenen", Price = 84.95m, ProductSizeId = 3 },
                        new { Id = 68, Amount = 20, Color = "Blauw", Description = "De Old Skool-schoen is een echte Vans-klassieker; een lage veterschoen die als eerste de iconische zijstreep droeg. De schoen is gevoerd, heeft gevoerde boorden voor steun en flexibiliteit en de verstevigde neus kan tegen een stootje.", ImageName = "https://images.vans.com/is/image/VansEU/VN000D3HY28-HERO?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=fgRQN2&wid=840&hei=840&fmt=jpg", Name = "Vans Old Skool", Price = 84.95m, ProductSizeId = 3 },
                        new { Id = 69, Amount = 20, Color = "Wit", Description = "De Vans Classic Slip-On is een lage instapper met elastiek aan de zijkanten en gevoerde boorden voor extra comfort. De schoen is voorzien van het Vans-vlaglogo en de kenmerkende wafelprofielzool staat garant voor een stevige grip.", ImageName = "https://images.vans.com/is/image/VansEU/VN000EYEBWW-HERO?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=1ucRN2&wid=840&hei=840&fmt=jpg", Name = "Vans Checkerboard", Price = 64.99m, ProductSizeId = 3 },
                        new { Id = 70, Amount = 20, Color = "Zwart", Description = "De archief-look van dit T-shirt vangt het gemak dat Italiaanse sportkleding in de jaren 80 uitstraalde. Karakteristieke 3-Stripes zijn in het historische design ingebreid. Het zachte T-shirt van mesh heeft een verfijnde, hoog opstaande kraag.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/45e6916b26714329aef5a944011a45df_9366/Stripes_T-shirt_blauw_DU7847_01_laydown.jpg", Name = "Adidas Stripes T-Shirt", Price = 44.95m, ProductSizeId = 3 },
                        new { Id = 71, Amount = 20, Color = "Grijs", Description = "Een onmisbaar item voor elke dag. Dit T-shirt heeft een strakke look met een geborduurd Trefoil-logo op de borst. Door de katoenen jersey voelt 't shirt zacht en comfortabel aan.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/e1ce80435eeb4501bd81a98f014ab60a_9366/Essential_T-shirt_grijs_DV1641_01_laydown.jpg", Name = "Adidas Essential T-Shirt", Price = 24.95m, ProductSizeId = 3 },
                        new { Id = 72, Amount = 20, Color = "Zwart", Description = "Jiro Bevis behoort zowat tot het meubilair van de Londense kunstwereld. Hij geeft het Trefoil-logo een frisse draai, met dit gedurfde T-shirt als resultaat. Het shirt van zachte, katoenen jersey heeft een casual recht silhouet.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/a361611d72334203af82a99a0155142b_9366/Thaxter_T-shirt_zwart_DU8367_01_laydown.jpg", Name = "Adidas Thaxter T-shirt", Price = 32.95m, ProductSizeId = 3 },
                        new { Id = 73, Amount = 20, Color = "Geel", Description = "Een onmisbaar item voor elke dag. Dit T-shirt heeft een strakke look met een geborduurd logo op de borst.", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2O/0C/EE/11/NI122O0CE-E11@2.jpg", Name = "Nike Club T-Shirt", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 74, Amount = 20, Color = "Wit", Description = "Een onmisbaar item voor elke dag. Dit T-shirt heeft een strakke look met een geborduurd logo op de borst.", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2O/0C/MA/11/NI122O0CM-A11@7.jpg", Name = "Nike Sport T-Shirt", Price = 19.95m, ProductSizeId = 3 },
                        new { Id = 75, Amount = 20, Color = "Zwart", Description = "Een onmisbaar item voor elke dag. Dit T-shirt heeft een strakke look met een geborduurd logo op de borst.", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2O/0C/WK/11/NI122O0CW-K11@9.2.jpg", Name = "Nike Brand T-Shirt", Price = 24.95m, ProductSizeId = 3 },
                        new { Id = 76, Amount = 20, Color = "Zwart", Description = "De PUMA x XO-samenwerking is er gekomen met dank aan de Canadese hiphopper The Weeknd en is een heruitvinden van de streetwear uit de jaren.", ImageName = "https://pumaimages.azureedge.net/images/578538/01/fnd/EEA/h/600/w/600", Name = "Puma x XO T-Shirt", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 77, Amount = 20, Color = "Groen", Description = "ATELIER NEW REGIME is het helemaal. Ze staan bekend om hun moderne ontwerpen waarin de Frans-Engelse culturele samensmelting is verwerkt die hun favoriete basis is.", ImageName = "https://pumaimages.azureedge.net/images/576564/02/fnd/EEA/h/600/w/600", Name = "Puma Camo T-Shirt", Price = 29.95m, ProductSizeId = 3 },
                        new { Id = 78, Amount = 20, Color = "Rood", Description = "Deze opvallende, gladde, sportieve top met korte mouwen van zachte katoenen jersey heeft gestreepte boordjes langs de hals en mouwen.", ImageName = "https://pumaimages.azureedge.net/images/845134/01/fnd/EEA/h/600/w/600", Name = "Puma T-Shirt", Price = 19.95m, ProductSizeId = 3 },
                        new { Id = 79, Amount = 20, Color = "Groen", Description = "Maak je look voor elke dag af met een klassiek heren-T-shirt. Het zachte katoen ademt van nature. ", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw62960709/zoom/DU4688_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Logo T-Shirt", Price = 19.95m, ProductSizeId = 3 },
                        new { Id = 80, Amount = 20, Color = "Zwart", Description = "Vier de geschiedenis van Reebok. Dit gemakkelijk te dragen T-shirt pronkt met een opvallend Vector-logo midden op de voorkant.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw03b16d0c/zoom/DT8245_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Classics T-shirt", Price = 39.95m, ProductSizeId = 3 },
                        new { Id = 81, Amount = 20, Color = "Groen", Description = "Het Vans Classic T-shirt heeft een ronde hals en korte mouwen, met kenmerkende Vans-logo-opdrukken op de voorkant en een klassieke pasvorm.", ImageName = "https://images.vans.com/is/image/VansEU/V00GGGRQI-ALT9?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=npnQ_2&wid=1043&hei=1044&fmt=jpg", Name = "Vans Classic T-shirt", Price = 19.95m, ProductSizeId = 3 },
                        new { Id = 82, Amount = 20, Color = "Wit", Description = "De Vans Classic Raglan heeft een ronde hals en driekwartraglanmouwen in contrastkleuren. Op de voorkant prijkt het Vans-logo.", ImageName = "https://images.vans.com/is/image/VansEU/VN0002QQWV5-ALT9?$VFDP-VIEWER-ZOOMVIEW-HERO$&id=CagRl0&wid=1043&hei=1044&fmt=jpg", Name = "Vans Classic Raglan", Price = 34.95m, ProductSizeId = 3 },
                        new { Id = 83, Amount = 20, Color = "Blauw", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/RE/32/2G/09/IK/11/RE322G09I-K11@8.jpg", Name = "Slim Fit Jeans", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 84, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/GS/12/2G/0D/QQ/11/GS122G0DQ-Q11@12.jpg", Name = "Zwarte Katoen Jeans", Price = 59.95m, ProductSizeId = 3 },
                        new { Id = 85, Amount = 20, Color = "Blauw", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/SI/F2/2G/00/RK/11/SIF22G00R-K11@8.jpg", Name = "Gescheurde Jeans", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 86, Amount = 20, Color = "Blauw", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/OS/32/2G/08/RK/11/OS322G08R-K11@18.1.jpg", Name = "Gescheurde Slim Fit Jeans ", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 87, Amount = 20, Color = "Zwart", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/C7/42/2G/00/AQ/11/C7422G00A-Q11@12.jpg", Name = "Black Spotted Jeans", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 88, Amount = 20, Color = "Grijs", Description = "", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/C7/42/2G/00/3Q/11/C7422G003-Q11@12.jpg", Name = "Grijze Skinny Fit", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 89, Amount = 20, Color = "Grijs", Description = "", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/BO/H2/2G/00/KC/11/BOH22G00K-C11@12.jpg", Name = "Grijze Biker Jeans", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 90, Amount = 20, Color = "Wit", Description = "Design uit het archief, vernieuwd voor nu. Deze hoodie valt op met geribbelde boorden en een subtiele, geborduurde Trefoil op de borst. ", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/5f79814d0aa04ac2bf6aa931012aa9d5_9366/Off_Court_Hoodie_grijs_DV3255_01_laydown.jpg", Name = "Adidas Off Court Hoodie", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 91, Amount = 20, Color = "Zwart", Description = "Buiten in de natuur zijn laagjes de sleutel tot een hele dag lang comfort. Dit sweatshirt blijft trouw aan het design van een klassieke hoodie, maar rust 'm uit voor onvoorspelbaar weer.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/5532dd7b650b4161b864a9180115bee7_9366/Team_Tech_Hoodie_zwart_CY8142_01_laydown.jpg", Name = "Adidas Team Tech Hoodie", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 92, Amount = 20, Color = "Zwart", Description = "Deze hoodie met rugbystijl brengt een eerbetoon aan de allesoverwinnende All Blacks. De sweater is gemaakt van zachte French terry badstof en pronkt met de beroemde zilveren varen.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/ac5fc274f7f4441c9cc0a88e00b18520_9366/All_Blacks_Hoodie_zwart_CW3116_01_laydown.jpg", Name = "Adidas All Blacks Hoodie", Price = 54.95m, ProductSizeId = 3 },
                        new { Id = 93, Amount = 20, Color = "Groen", Description = "Mooie Nike Hoodie", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2S/09/9G/11/NI122S099-G11@11.1.jpg", Name = "Nike Camo Hoodie", Price = 67.95m, ProductSizeId = 3 },
                        new { Id = 94, Amount = 20, Color = "Rood", Description = "Mooie Nike Hoodie", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NS/42/2S/01/GG/11/NS422S01G-G11@13.1.jpg", Name = "Nike SB Hoodie", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 95, Amount = 20, Color = "Grijs", Description = "Mooie Nike Hoodie", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2S/08/NN/11/NI122S08N-N11@12.jpg", Name = "Nike Box Hoodie", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 96, Amount = 20, Color = "Rood", Description = "PUMA's reputatie van innovatieve en altijd comfortabele street style zet door met deze extra warme geruite hoodie van polaire fleece.", ImageName = "https://pumaimages.azureedge.net/images/578984/18/fnd/EEA/h/600/w/600", Name = "Puma Geruite Hoodie", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 97, Amount = 20, Color = "Zwart", Description = "Deze PUMA Eva sweater van katoenmix met capuchon heeft een modieuze stijl, strakke sportieve look en superzacht comfort.", ImageName = "https://pumaimages.azureedge.net/images/579702/03/fnd/EEA/h/600/w/600", Name = "Puma Evolution Hoodie", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 98, Amount = 20, Color = "Geel", Description = "Een retro look voor je hoodieverzameling. Deze beproefde stijl laat zijn geschiedenis zien. Dit herensweatshirt heeft grafische tape langs de mouwen en het Starcrest-logo op de borst.", ImageName = "https://www.reebok.nl/dis/dw/image/v2/AAJP_PRD/on/demandware.static/-/Sites-reebok-products/default/dw2038752d/zoom/DT8155_01_standard.jpg?sh=840&strip=false&sw=840", Name = "Reebok Tape Hoodie", Price = 69.95m, ProductSizeId = 3 },
                        new { Id = 99, Amount = 20, Color = "Groen", Description = "Stukken met camouflageprint maken deze streetwear-basic extra edgy. Voor een zacht en comfortabel gevoel is de hoodie gemaakt van katoenen French terry badstof.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/404cbde04ee64564aaa9a97b013b409d_9366/Camouflage_Hoodie_zwart_DV2019_01_laydown.jpg", Name = "Adidas Camo vest", Price = 79.95m, ProductSizeId = 3 },
                        new { Id = 100, Amount = 20, Color = "Grijs", Description = "Deze herenhoodie is gemaakt van zachte French terry badstof met katoen om je behaaglijk en comfortabel te houden.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/5d1ba0e117f345e99212a81000bba68a_9366/Essentials_3-Stripes_Hoodie_grijs_S98788_01_laydown.jpg", Name = "Adidas Sport Vest", Price = 59.95m, ProductSizeId = 3 },
                        new { Id = 101, Amount = 20, Color = "Groen", Description = "Adicolor staat al sinds 1983 voor creativiteit en zelfexpressie. Deze hoodie houdt de Adicolor-look levend. Het comfortabele, relaxte model is gemaakt van geweven polyester.", ImageName = "https://assets.adidas.com/images/w_840,h_840,f_auto,q_90,fl_lossy/4354bf68b1a54ddba625a9a800f2c682_9366/Outline_Hoodie_blauw_DX3855_01_laydown.jpg", Name = "Adidas Outline Hoodie", Price = 59.95m, ProductSizeId = 3 },
                        new { Id = 102, Amount = 20, Color = "Zwart", Description = "Mooie Nike Vest", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2S/08/BK/11/NI122S08B-K11@12.jpg", Name = "Nike Tech Vest", Price = 89.95m, ProductSizeId = 3 },
                        new { Id = 103, Amount = 20, Color = "Grijs", Description = "Mooie Nike Vest", ImageName = "https://mosaic04.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2S/05/8C/11/NI122S058-C11@12.jpg", Name = "Nike Club Vest", Price = 49.95m, ProductSizeId = 3 },
                        new { Id = 104, Amount = 20, Color = "Grijs", Description = "Mooie Nike Vest", ImageName = "https://mosaic03.ztat.net/vgs/media/packshot/pdp-zoom/NI/12/2S/08/PC/11/NI122S08P-C11@4.jpg", Name = "Nike Sport Vest", Price = 49.95m, ProductSizeId = 3 }
                    );
                });

            modelBuilder.Entity("backend.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, ProductId = 1 },
                        new { Id = 2, CategoryId = 3, ProductId = 1 },
                        new { Id = 3, CategoryId = 8, ProductId = 1 },
                        new { Id = 4, CategoryId = 1, ProductId = 2 },
                        new { Id = 5, CategoryId = 3, ProductId = 2 },
                        new { Id = 6, CategoryId = 8, ProductId = 2 },
                        new { Id = 7, CategoryId = 1, ProductId = 3 },
                        new { Id = 8, CategoryId = 3, ProductId = 3 },
                        new { Id = 9, CategoryId = 8, ProductId = 3 },
                        new { Id = 10, CategoryId = 1, ProductId = 4 },
                        new { Id = 11, CategoryId = 3, ProductId = 4 },
                        new { Id = 12, CategoryId = 9, ProductId = 4 },
                        new { Id = 13, CategoryId = 1, ProductId = 5 },
                        new { Id = 14, CategoryId = 3, ProductId = 5 },
                        new { Id = 15, CategoryId = 9, ProductId = 5 },
                        new { Id = 16, CategoryId = 1, ProductId = 6 },
                        new { Id = 17, CategoryId = 3, ProductId = 6 },
                        new { Id = 18, CategoryId = 9, ProductId = 6 },
                        new { Id = 19, CategoryId = 1, ProductId = 7 },
                        new { Id = 20, CategoryId = 3, ProductId = 7 },
                        new { Id = 21, CategoryId = 11, ProductId = 7 },
                        new { Id = 22, CategoryId = 1, ProductId = 8 },
                        new { Id = 23, CategoryId = 3, ProductId = 8 },
                        new { Id = 24, CategoryId = 11, ProductId = 8 },
                        new { Id = 25, CategoryId = 1, ProductId = 9 },
                        new { Id = 26, CategoryId = 3, ProductId = 9 },
                        new { Id = 27, CategoryId = 11, ProductId = 9 },
                        new { Id = 28, CategoryId = 1, ProductId = 10 },
                        new { Id = 29, CategoryId = 3, ProductId = 10 },
                        new { Id = 30, CategoryId = 12, ProductId = 10 },
                        new { Id = 31, CategoryId = 1, ProductId = 11 },
                        new { Id = 32, CategoryId = 3, ProductId = 11 },
                        new { Id = 33, CategoryId = 12, ProductId = 11 },
                        new { Id = 34, CategoryId = 1, ProductId = 12 },
                        new { Id = 35, CategoryId = 3, ProductId = 12 },
                        new { Id = 36, CategoryId = 13, ProductId = 12 },
                        new { Id = 37, CategoryId = 1, ProductId = 13 },
                        new { Id = 38, CategoryId = 3, ProductId = 13 },
                        new { Id = 39, CategoryId = 13, ProductId = 13 },
                        new { Id = 40, CategoryId = 1, ProductId = 14 },
                        new { Id = 41, CategoryId = 3, ProductId = 14 },
                        new { Id = 42, CategoryId = 14, ProductId = 14 },
                        new { Id = 43, CategoryId = 1, ProductId = 15 },
                        new { Id = 44, CategoryId = 3, ProductId = 15 },
                        new { Id = 45, CategoryId = 14, ProductId = 15 },
                        new { Id = 46, CategoryId = 1, ProductId = 16 },
                        new { Id = 47, CategoryId = 4, ProductId = 16 },
                        new { Id = 48, CategoryId = 8, ProductId = 16 },
                        new { Id = 49, CategoryId = 1, ProductId = 17 },
                        new { Id = 50, CategoryId = 4, ProductId = 17 },
                        new { Id = 51, CategoryId = 8, ProductId = 17 },
                        new { Id = 52, CategoryId = 1, ProductId = 18 },
                        new { Id = 53, CategoryId = 4, ProductId = 18 },
                        new { Id = 54, CategoryId = 8, ProductId = 18 },
                        new { Id = 55, CategoryId = 1, ProductId = 19 },
                        new { Id = 56, CategoryId = 4, ProductId = 19 },
                        new { Id = 57, CategoryId = 9, ProductId = 19 },
                        new { Id = 58, CategoryId = 1, ProductId = 20 },
                        new { Id = 59, CategoryId = 4, ProductId = 20 },
                        new { Id = 60, CategoryId = 9, ProductId = 20 },
                        new { Id = 61, CategoryId = 1, ProductId = 21 },
                        new { Id = 62, CategoryId = 4, ProductId = 21 },
                        new { Id = 63, CategoryId = 9, ProductId = 21 },
                        new { Id = 64, CategoryId = 1, ProductId = 22 },
                        new { Id = 65, CategoryId = 4, ProductId = 22 },
                        new { Id = 66, CategoryId = 11, ProductId = 22 },
                        new { Id = 67, CategoryId = 1, ProductId = 23 },
                        new { Id = 68, CategoryId = 4, ProductId = 23 },
                        new { Id = 69, CategoryId = 11, ProductId = 23 },
                        new { Id = 70, CategoryId = 1, ProductId = 24 },
                        new { Id = 71, CategoryId = 4, ProductId = 24 },
                        new { Id = 72, CategoryId = 11, ProductId = 24 },
                        new { Id = 73, CategoryId = 1, ProductId = 25 },
                        new { Id = 74, CategoryId = 4, ProductId = 25 },
                        new { Id = 75, CategoryId = 13, ProductId = 25 },
                        new { Id = 76, CategoryId = 1, ProductId = 26 },
                        new { Id = 77, CategoryId = 4, ProductId = 26 },
                        new { Id = 78, CategoryId = 13, ProductId = 26 },
                        new { Id = 79, CategoryId = 1, ProductId = 27 },
                        new { Id = 80, CategoryId = 4, ProductId = 27 },
                        new { Id = 81, CategoryId = 14, ProductId = 27 },
                        new { Id = 82, CategoryId = 1, ProductId = 28 },
                        new { Id = 83, CategoryId = 4, ProductId = 28 },
                        new { Id = 84, CategoryId = 14, ProductId = 28 },
                        new { Id = 85, CategoryId = 1, ProductId = 29 },
                        new { Id = 86, CategoryId = 5, ProductId = 29 },
                        new { Id = 87, CategoryId = 10, ProductId = 29 },
                        new { Id = 88, CategoryId = 1, ProductId = 30 },
                        new { Id = 89, CategoryId = 5, ProductId = 30 },
                        new { Id = 90, CategoryId = 10, ProductId = 30 },
                        new { Id = 91, CategoryId = 1, ProductId = 31 },
                        new { Id = 92, CategoryId = 5, ProductId = 31 },
                        new { Id = 93, CategoryId = 10, ProductId = 31 },
                        new { Id = 94, CategoryId = 1, ProductId = 32 },
                        new { Id = 95, CategoryId = 5, ProductId = 32 },
                        new { Id = 96, CategoryId = 10, ProductId = 32 },
                        new { Id = 97, CategoryId = 1, ProductId = 33 },
                        new { Id = 98, CategoryId = 5, ProductId = 33 },
                        new { Id = 99, CategoryId = 10, ProductId = 33 },
                        new { Id = 100, CategoryId = 1, ProductId = 34 },
                        new { Id = 101, CategoryId = 5, ProductId = 34 },
                        new { Id = 102, CategoryId = 10, ProductId = 34 },
                        new { Id = 103, CategoryId = 1, ProductId = 35 },
                        new { Id = 104, CategoryId = 5, ProductId = 35 },
                        new { Id = 105, CategoryId = 10, ProductId = 35 },
                        new { Id = 106, CategoryId = 1, ProductId = 36 },
                        new { Id = 107, CategoryId = 5, ProductId = 36 },
                        new { Id = 108, CategoryId = 10, ProductId = 36 },
                        new { Id = 109, CategoryId = 1, ProductId = 37 },
                        new { Id = 110, CategoryId = 6, ProductId = 37 },
                        new { Id = 111, CategoryId = 8, ProductId = 37 },
                        new { Id = 112, CategoryId = 1, ProductId = 38 },
                        new { Id = 113, CategoryId = 6, ProductId = 38 },
                        new { Id = 114, CategoryId = 8, ProductId = 38 },
                        new { Id = 115, CategoryId = 1, ProductId = 39 },
                        new { Id = 116, CategoryId = 6, ProductId = 39 },
                        new { Id = 117, CategoryId = 8, ProductId = 39 },
                        new { Id = 118, CategoryId = 1, ProductId = 40 },
                        new { Id = 119, CategoryId = 6, ProductId = 40 },
                        new { Id = 120, CategoryId = 9, ProductId = 40 },
                        new { Id = 121, CategoryId = 1, ProductId = 41 },
                        new { Id = 122, CategoryId = 6, ProductId = 41 },
                        new { Id = 123, CategoryId = 9, ProductId = 41 },
                        new { Id = 124, CategoryId = 1, ProductId = 42 },
                        new { Id = 125, CategoryId = 6, ProductId = 42 },
                        new { Id = 126, CategoryId = 9, ProductId = 42 },
                        new { Id = 127, CategoryId = 1, ProductId = 43 },
                        new { Id = 128, CategoryId = 6, ProductId = 43 },
                        new { Id = 129, CategoryId = 11, ProductId = 43 },
                        new { Id = 130, CategoryId = 1, ProductId = 44 },
                        new { Id = 131, CategoryId = 6, ProductId = 44 },
                        new { Id = 132, CategoryId = 11, ProductId = 44 },
                        new { Id = 133, CategoryId = 1, ProductId = 45 },
                        new { Id = 134, CategoryId = 6, ProductId = 45 },
                        new { Id = 135, CategoryId = 11, ProductId = 45 },
                        new { Id = 136, CategoryId = 1, ProductId = 46 },
                        new { Id = 137, CategoryId = 6, ProductId = 46 },
                        new { Id = 138, CategoryId = 13, ProductId = 46 },
                        new { Id = 139, CategoryId = 1, ProductId = 47 },
                        new { Id = 140, CategoryId = 7, ProductId = 47 },
                        new { Id = 141, CategoryId = 8, ProductId = 47 },
                        new { Id = 142, CategoryId = 1, ProductId = 48 },
                        new { Id = 143, CategoryId = 7, ProductId = 48 },
                        new { Id = 144, CategoryId = 8, ProductId = 48 },
                        new { Id = 145, CategoryId = 1, ProductId = 49 },
                        new { Id = 146, CategoryId = 7, ProductId = 49 },
                        new { Id = 147, CategoryId = 8, ProductId = 49 },
                        new { Id = 148, CategoryId = 1, ProductId = 50 },
                        new { Id = 149, CategoryId = 6, ProductId = 50 },
                        new { Id = 150, CategoryId = 9, ProductId = 50 },
                        new { Id = 151, CategoryId = 1, ProductId = 51 },
                        new { Id = 152, CategoryId = 6, ProductId = 51 },
                        new { Id = 153, CategoryId = 9, ProductId = 51 },
                        new { Id = 154, CategoryId = 1, ProductId = 52 },
                        new { Id = 155, CategoryId = 7, ProductId = 52 },
                        new { Id = 156, CategoryId = 13, ProductId = 52 },
                        new { Id = 157, CategoryId = 2, ProductId = 53 },
                        new { Id = 158, CategoryId = 3, ProductId = 53 },
                        new { Id = 159, CategoryId = 9, ProductId = 53 },
                        new { Id = 160, CategoryId = 2, ProductId = 54 },
                        new { Id = 161, CategoryId = 3, ProductId = 54 },
                        new { Id = 162, CategoryId = 9, ProductId = 54 },
                        new { Id = 163, CategoryId = 2, ProductId = 55 },
                        new { Id = 164, CategoryId = 3, ProductId = 55 },
                        new { Id = 165, CategoryId = 9, ProductId = 55 },
                        new { Id = 166, CategoryId = 2, ProductId = 56 },
                        new { Id = 167, CategoryId = 3, ProductId = 56 },
                        new { Id = 168, CategoryId = 8, ProductId = 56 },
                        new { Id = 169, CategoryId = 2, ProductId = 57 },
                        new { Id = 170, CategoryId = 3, ProductId = 57 },
                        new { Id = 171, CategoryId = 8, ProductId = 57 },
                        new { Id = 172, CategoryId = 2, ProductId = 58 },
                        new { Id = 173, CategoryId = 3, ProductId = 58 },
                        new { Id = 174, CategoryId = 8, ProductId = 58 },
                        new { Id = 175, CategoryId = 2, ProductId = 59 },
                        new { Id = 176, CategoryId = 3, ProductId = 59 },
                        new { Id = 177, CategoryId = 11, ProductId = 59 },
                        new { Id = 178, CategoryId = 2, ProductId = 60 },
                        new { Id = 179, CategoryId = 3, ProductId = 60 },
                        new { Id = 180, CategoryId = 11, ProductId = 60 },
                        new { Id = 181, CategoryId = 2, ProductId = 61 },
                        new { Id = 182, CategoryId = 3, ProductId = 61 },
                        new { Id = 183, CategoryId = 11, ProductId = 61 },
                        new { Id = 184, CategoryId = 2, ProductId = 62 },
                        new { Id = 185, CategoryId = 3, ProductId = 62 },
                        new { Id = 186, CategoryId = 12, ProductId = 62 },
                        new { Id = 187, CategoryId = 2, ProductId = 63 },
                        new { Id = 188, CategoryId = 3, ProductId = 63 },
                        new { Id = 189, CategoryId = 12, ProductId = 63 },
                        new { Id = 190, CategoryId = 2, ProductId = 64 },
                        new { Id = 191, CategoryId = 3, ProductId = 64 },
                        new { Id = 192, CategoryId = 13, ProductId = 64 },
                        new { Id = 193, CategoryId = 2, ProductId = 65 },
                        new { Id = 194, CategoryId = 3, ProductId = 65 },
                        new { Id = 195, CategoryId = 13, ProductId = 65 },
                        new { Id = 196, CategoryId = 2, ProductId = 66 },
                        new { Id = 197, CategoryId = 3, ProductId = 66 },
                        new { Id = 198, CategoryId = 13, ProductId = 66 },
                        new { Id = 199, CategoryId = 2, ProductId = 67 },
                        new { Id = 200, CategoryId = 3, ProductId = 67 },
                        new { Id = 201, CategoryId = 14, ProductId = 67 },
                        new { Id = 202, CategoryId = 2, ProductId = 68 },
                        new { Id = 203, CategoryId = 3, ProductId = 68 },
                        new { Id = 204, CategoryId = 14, ProductId = 68 },
                        new { Id = 205, CategoryId = 2, ProductId = 69 },
                        new { Id = 206, CategoryId = 3, ProductId = 69 },
                        new { Id = 207, CategoryId = 14, ProductId = 69 },
                        new { Id = 208, CategoryId = 2, ProductId = 70 },
                        new { Id = 209, CategoryId = 4, ProductId = 70 },
                        new { Id = 210, CategoryId = 8, ProductId = 70 },
                        new { Id = 211, CategoryId = 2, ProductId = 71 },
                        new { Id = 212, CategoryId = 4, ProductId = 71 },
                        new { Id = 213, CategoryId = 8, ProductId = 71 },
                        new { Id = 214, CategoryId = 2, ProductId = 72 },
                        new { Id = 215, CategoryId = 4, ProductId = 72 },
                        new { Id = 216, CategoryId = 8, ProductId = 72 },
                        new { Id = 217, CategoryId = 2, ProductId = 73 },
                        new { Id = 218, CategoryId = 4, ProductId = 73 },
                        new { Id = 219, CategoryId = 9, ProductId = 73 },
                        new { Id = 220, CategoryId = 2, ProductId = 74 },
                        new { Id = 221, CategoryId = 4, ProductId = 74 },
                        new { Id = 222, CategoryId = 9, ProductId = 74 },
                        new { Id = 223, CategoryId = 2, ProductId = 75 },
                        new { Id = 224, CategoryId = 4, ProductId = 75 },
                        new { Id = 225, CategoryId = 9, ProductId = 75 },
                        new { Id = 226, CategoryId = 2, ProductId = 76 },
                        new { Id = 227, CategoryId = 4, ProductId = 76 },
                        new { Id = 228, CategoryId = 11, ProductId = 76 },
                        new { Id = 229, CategoryId = 2, ProductId = 77 },
                        new { Id = 230, CategoryId = 4, ProductId = 77 },
                        new { Id = 231, CategoryId = 11, ProductId = 77 },
                        new { Id = 232, CategoryId = 2, ProductId = 78 },
                        new { Id = 233, CategoryId = 4, ProductId = 78 },
                        new { Id = 234, CategoryId = 11, ProductId = 78 },
                        new { Id = 235, CategoryId = 2, ProductId = 79 },
                        new { Id = 236, CategoryId = 4, ProductId = 79 },
                        new { Id = 237, CategoryId = 13, ProductId = 79 },
                        new { Id = 238, CategoryId = 2, ProductId = 80 },
                        new { Id = 239, CategoryId = 4, ProductId = 80 },
                        new { Id = 240, CategoryId = 13, ProductId = 80 },
                        new { Id = 241, CategoryId = 2, ProductId = 81 },
                        new { Id = 242, CategoryId = 4, ProductId = 81 },
                        new { Id = 243, CategoryId = 14, ProductId = 81 },
                        new { Id = 244, CategoryId = 2, ProductId = 82 },
                        new { Id = 245, CategoryId = 4, ProductId = 82 },
                        new { Id = 246, CategoryId = 14, ProductId = 82 },
                        new { Id = 247, CategoryId = 2, ProductId = 83 },
                        new { Id = 248, CategoryId = 5, ProductId = 83 },
                        new { Id = 249, CategoryId = 10, ProductId = 83 },
                        new { Id = 250, CategoryId = 2, ProductId = 84 },
                        new { Id = 251, CategoryId = 5, ProductId = 84 },
                        new { Id = 252, CategoryId = 10, ProductId = 84 },
                        new { Id = 253, CategoryId = 2, ProductId = 85 },
                        new { Id = 254, CategoryId = 5, ProductId = 85 },
                        new { Id = 255, CategoryId = 10, ProductId = 85 },
                        new { Id = 256, CategoryId = 2, ProductId = 86 },
                        new { Id = 257, CategoryId = 5, ProductId = 86 },
                        new { Id = 258, CategoryId = 10, ProductId = 86 },
                        new { Id = 259, CategoryId = 2, ProductId = 87 },
                        new { Id = 260, CategoryId = 5, ProductId = 87 },
                        new { Id = 261, CategoryId = 10, ProductId = 87 },
                        new { Id = 262, CategoryId = 2, ProductId = 88 },
                        new { Id = 263, CategoryId = 5, ProductId = 88 },
                        new { Id = 264, CategoryId = 10, ProductId = 88 },
                        new { Id = 265, CategoryId = 2, ProductId = 89 },
                        new { Id = 266, CategoryId = 5, ProductId = 89 },
                        new { Id = 267, CategoryId = 10, ProductId = 89 },
                        new { Id = 268, CategoryId = 2, ProductId = 90 },
                        new { Id = 269, CategoryId = 6, ProductId = 90 },
                        new { Id = 270, CategoryId = 8, ProductId = 90 },
                        new { Id = 271, CategoryId = 2, ProductId = 91 },
                        new { Id = 272, CategoryId = 6, ProductId = 91 },
                        new { Id = 273, CategoryId = 8, ProductId = 91 },
                        new { Id = 274, CategoryId = 2, ProductId = 92 },
                        new { Id = 275, CategoryId = 6, ProductId = 92 },
                        new { Id = 276, CategoryId = 8, ProductId = 92 },
                        new { Id = 277, CategoryId = 2, ProductId = 93 },
                        new { Id = 278, CategoryId = 6, ProductId = 93 },
                        new { Id = 279, CategoryId = 9, ProductId = 93 },
                        new { Id = 280, CategoryId = 2, ProductId = 94 },
                        new { Id = 281, CategoryId = 6, ProductId = 94 },
                        new { Id = 282, CategoryId = 9, ProductId = 94 },
                        new { Id = 283, CategoryId = 2, ProductId = 95 },
                        new { Id = 284, CategoryId = 6, ProductId = 95 },
                        new { Id = 285, CategoryId = 9, ProductId = 95 },
                        new { Id = 286, CategoryId = 2, ProductId = 96 },
                        new { Id = 287, CategoryId = 6, ProductId = 96 },
                        new { Id = 288, CategoryId = 11, ProductId = 96 },
                        new { Id = 289, CategoryId = 2, ProductId = 97 },
                        new { Id = 290, CategoryId = 6, ProductId = 97 },
                        new { Id = 291, CategoryId = 11, ProductId = 97 },
                        new { Id = 292, CategoryId = 2, ProductId = 98 },
                        new { Id = 293, CategoryId = 6, ProductId = 98 },
                        new { Id = 294, CategoryId = 13, ProductId = 98 },
                        new { Id = 295, CategoryId = 2, ProductId = 99 },
                        new { Id = 296, CategoryId = 7, ProductId = 99 },
                        new { Id = 297, CategoryId = 8, ProductId = 99 },
                        new { Id = 298, CategoryId = 2, ProductId = 100 },
                        new { Id = 299, CategoryId = 7, ProductId = 100 },
                        new { Id = 300, CategoryId = 8, ProductId = 100 },
                        new { Id = 301, CategoryId = 2, ProductId = 101 },
                        new { Id = 302, CategoryId = 7, ProductId = 101 },
                        new { Id = 303, CategoryId = 8, ProductId = 101 },
                        new { Id = 304, CategoryId = 2, ProductId = 102 },
                        new { Id = 305, CategoryId = 7, ProductId = 102 },
                        new { Id = 306, CategoryId = 9, ProductId = 102 },
                        new { Id = 307, CategoryId = 2, ProductId = 103 },
                        new { Id = 308, CategoryId = 7, ProductId = 103 },
                        new { Id = 309, CategoryId = 9, ProductId = 103 },
                        new { Id = 310, CategoryId = 2, ProductId = 104 },
                        new { Id = 311, CategoryId = 7, ProductId = 104 },
                        new { Id = 312, CategoryId = 9, ProductId = 104 }
                    );
                });

            modelBuilder.Entity("backend.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SizeName");

                    b.HasKey("Id");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new { Id = 1, SizeName = "XS" },
                        new { Id = 2, SizeName = "S" },
                        new { Id = 3, SizeName = "M" },
                        new { Id = 4, SizeName = "L" },
                        new { Id = 5, SizeName = "XL" },
                        new { Id = 6, SizeName = "XXL" },
                        new { Id = 7, SizeName = "34" },
                        new { Id = 8, SizeName = "35" },
                        new { Id = 9, SizeName = "36" },
                        new { Id = 10, SizeName = "37" },
                        new { Id = 11, SizeName = "38" },
                        new { Id = 12, SizeName = "39" },
                        new { Id = 13, SizeName = "40" },
                        new { Id = 14, SizeName = "41" },
                        new { Id = 15, SizeName = "42" },
                        new { Id = 16, SizeName = "43" },
                        new { Id = 17, SizeName = "44" },
                        new { Id = 18, SizeName = "45" },
                        new { Id = 19, SizeName = "46" },
                        new { Id = 20, SizeName = "47" },
                        new { Id = 21, SizeName = "48" },
                        new { Id = 22, SizeName = "49" }
                    );
                });

            modelBuilder.Entity("backend.Models.ProductSold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductsSold");
                });

            modelBuilder.Entity("backend.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new { Id = 1, Description = "The transaction has been marked for review, typically by the payment gateway.", Name = "Review" },
                        new { Id = 2, Description = "The the purchase order for the transaction has been created.This status is set at the very onset of the transaction, typically before the invoiced balance is set, and before the paymentis authorized or paid.", Name = "Purchase Order" },
                        new { Id = 3, Description = "The transaction is invoiced, and the order total becomes an open balance.", Name = "Invoiced" },
                        new { Id = 4, Description = "The payment for the transaction has been authorized by the payment gateway.", Name = "Authorized" },
                        new { Id = 5, Description = "The payment for the transaction has been accepted by the payment gateway.", Name = "Paid" },
                        new { Id = 6, Description = "The order has been marked as shipped by the merchant.", Name = "Shipped" },
                        new { Id = 7, Description = "The payment for the transaction has been refunded.", Name = "Refunded" },
                        new { Id = 8, Description = "The balance on the transaction has been voided.", Name = "Voided" },
                        new { Id = 9, Description = "The order is delivered to the client.", Name = "Delivered" }
                    );
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateOn")
                        .HasMaxLength(15);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Gender");

                    b.Property<string>("Key");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("Rank");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, CreateOn = new DateTime(2019, 1, 9, 13, 57, 23, 197, DateTimeKind.Local), Email = "admin@hrfashion.nl", Key = "smcJ/dBZATN4Mn117ExHtUwi6xA=", Name = "admin", Rank = 4, Salt = "Ukp7BqmIS61j+hZQ0BowmIKycaQ=" }
                    );
                });

            modelBuilder.Entity("backend.Models.WishListProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("WishListProducts");
                });

            modelBuilder.Entity("backend.Models.Address", b =>
                {
                    b.HasOne("backend.Models.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Discount", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithOne("Discount")
                        .HasForeignKey("backend.Models.Discount", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Order", b =>
                {
                    b.HasOne("backend.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Status", "Status")
                        .WithMany("Order")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.HasOne("backend.Models.ProductSize", "ProductSize")
                        .WithMany("Products")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.ProductCategory", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.ProductSold", b =>
                {
                    b.HasOne("backend.Models.Order", "Order")
                        .WithMany("ProductsSold")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Product", "Product")
                        .WithOne("ProductSold")
                        .HasForeignKey("backend.Models.ProductSold", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ProductsSold")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.WishListProduct", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("WishListProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("WishListProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
